### ISSUE TITLE
Have to reset Arduino to get things working

### ISSUE THREAD

**Issue by MarkJB** [MarkJB/pi-2-stepper-board#6]
When I run vPiP (python test1.py) the program sits at Polargraph **exit** until I reset the Arduino at which point the servo does its down-up-down move and then the steppers work...

Perhaps the original program is expecting the Arduino to reset upon connect. I don't think the Pro Minis do that as they don't have the USB serial port reset on connect feature that some Arduinos seem to have.

Maybe the firmware isn't sending a 'hello' type command except at reset?

**Comment by brianinnes** [comment]
The only thing done with the serial port in the setup routine of the Arduino code is : 

```
  Serial.begin(57600);
  Serial.setTimeout(0);
```

There are a few GPIO pin setup commands then the servo code config runs : 

```
  penUpServo.attach(PENUP_SERVO_PIN);
  penUpServo.write(PENUP_ANGLE);
  delay(1000);
  penUpServo.write(PENDOWN_ANGLE);
  delay(1000);
  penUpServo.write(PENUP_ANGLE);
```

so the servo should cycle at power up before any serial comms takes place.

**Comment by MarkJB** [comment]
I've been trying to track the issue down.

I've managed to get the Arduino IDE running on the Pi and am able to program the Pro Mini directly over the GPIO. I have to reset the Arduino the instant the IDE says 'Uploading' for it to work but that is normal for a Pro Mini.

I uploaded a serial echo program and was able to see chars echoed to the Arduino and back via minicom on the Pi.

I reuploaded the stepper firmware and the servo did its up-down-up move.

I tried running python test1.py but it hangs until I reset the pro mini which is why I was thinking the serial comms is out of sync or not doing a 'hello' type command.

I shutdown, powered off and powered on the whole thing and sure enough the servo did its up-down-up move. But python test1.py still hangs until I reset the Arduino.

**Comment by MarkJB** [comment]
I left it sitting to see if the serial comms would timeout and start running but it didn't.

**Comment by MarkJB** [comment]
Added some debugging on the Arduino serial coms and it does appear to be timing out and requesting more data, but vPiP isn't hearing or responding to it, or is out of sync.

I can watch the moveDataRequestPending value being set to 128 when requestMoreSerialData() is run.

It then decrements as if data is being read. 

The data being read is 'ó' (ASCII 224).

When moveDataRequestPending reaches 0 the Arduino asks for more data and it carries on like that but nothing useful happens (motors don't move).

Brian, I'm punting this across to vPiP for you to have a look at when you have a board up and running.
